/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 su35.gltf 
Author: bohmerang (https://sketchfab.com/bohmerang)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/sukhoi-su-35-fighter-jet-free-3213a404e5cb4fb68f778b9acae5109c
Title: Sukhoi Su-35 - Fighter Jet - Free
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/su35.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials['SU-35-airframe']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.Glass} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_8.geometry} material={materials['SU-35-airframe']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_10.geometry} material={materials['SU-35-hud']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.Glass} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_14.geometry} material={materials['SU-35-airframe']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_16.geometry} material={materials['SU-35-airframe']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_18.geometry} material={materials['SU-35-landinglights']} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/su35.gltf')
